[package]
name = "kstu"
version = "0.1.0"
edition = "2021"

[dependencies]
isahc = "1.7.2"
itertools = "0.10.5"
scraper = "0.15.0"
thiserror = "1.0.38"
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
futures-executor = "0.3.26"
pretty_assertions = "1.3.0"
tracing-subscriber = "0.3.16"
