[package]
name = "kstu"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.14"
scraper = "0.15.0"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
tracing-subscriber = "0.3.16"
